### ISSUE TITLE
Event Page TODO

### ISSUE THREAD

**Issue by shiweing** [cs3216-2021-a3-group12/slotify-frontend#9]
- [x] View event (YL)
- [x] Sign up for event / Waiting list
- [x] Mark attendance for admins
